### ISSUE TITLE
Only one level of Map nesting is supported for defining plugins

### ISSUE THREAD

**Issue by pmellati** [jcouyang/buildkite.dhall#3]
Given the current definition of `Plugin`:

```dhall
let PluginConfig = Map Text Text

let Plugin = Map Text PluginConfig
```

The following real-world buildkite plugin cannot be represented:

```yaml
plugins:
    - seek-oss/aws-sm#v2.3.1:
        env:
          GRADLE_BUILD_CACHE_PASSWORD: /my/password
```

Looks like more levels of `Map` nesting are required to be able to represent certain buildkite plugins.
